// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvr6sZbCgN_Lt6AexHz8jcdm3nzo6Nq0',
    appId: '1:715004253991:web:d644ad3fa4aa8f5cc53b02',
    messagingSenderId: '715004253991',
    projectId: 'riciclozen',
    authDomain: 'riciclozen.firebaseapp.com',
    databaseURL: 'https://riciclozen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riciclozen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0j8Jcum7MrJbdwGw5EcsumJIPbjwYxA',
    appId: '1:715004253991:android:41db3506981d68d4c53b02',
    messagingSenderId: '715004253991',
    projectId: 'riciclozen',
    databaseURL: 'https://riciclozen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riciclozen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4VC8z5qmuoyMRTv4GGUAW9IiPLOY4azI',
    appId: '1:715004253991:ios:65ec05a32b568436c53b02',
    messagingSenderId: '715004253991',
    projectId: 'riciclozen',
    databaseURL: 'https://riciclozen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riciclozen.appspot.com',
    iosBundleId: 'com.example.ricicloZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4VC8z5qmuoyMRTv4GGUAW9IiPLOY4azI',
    appId: '1:715004253991:ios:65ec05a32b568436c53b02',
    messagingSenderId: '715004253991',
    projectId: 'riciclozen',
    databaseURL: 'https://riciclozen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riciclozen.appspot.com',
    iosBundleId: 'com.example.ricicloZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvr6sZbCgN_Lt6AexHz8jcdm3nzo6Nq0',
    appId: '1:715004253991:web:79623965ebefdbb1c53b02',
    messagingSenderId: '715004253991',
    projectId: 'riciclozen',
    authDomain: 'riciclozen.firebaseapp.com',
    databaseURL: 'https://riciclozen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riciclozen.appspot.com',
  );

}